### ISSUE TITLE
Support custom models

### ISSUE THREAD

**Issue by azihsoyn** [azihsoyn/flutter_mlkit#21]
https://firebase.google.com/docs/ml-kit/use-custom-models

for https://github.com/flutter/flutter/issues/17532#issuecomment-396784526

**Comment by startupgurukul** [comment]
Thanks for promptly dedicating effort to work on this, a thought, what do you think about adding custom models support thru a plugin on its own, 

https://github.com/flutter/flutter/issues/18660 this issue was moved to a stretch goals and considering official MLVision plugin your support for custom models can come i handy for a lot of users

**Comment by azihsoyn** [comment]
Hi, @startupgurukul !

I think flutter_mlkit user should use the official plugin (flutter_ml_vision, flutter_ml_interperter?).
Of course, I am planning to send Pull-Request about custom model support, if it worked good.

I think this project is experimental before sending Pull-Request to official plugin.

**Comment by startupgurukul** [comment]
Looking forward. Will keep track of the pull request https://github.com/azihsoyn/flutter_mlkit/pull/27

**Comment by azihsoyn** [comment]
Thanks! I got motivated.

**Comment by azihsoyn** [comment]
Custom model interpreter for android released!
https://pub.dartlang.org/packages/mlkit

iOS support will be next release.

**Comment by gimox** [comment]
Fantastic!!! Waiting for iOS version👍👍👍👍👍

**Comment by azihsoyn** [comment]
iOS version already released.

Sorry late announcing.

**Comment by justus-hildebrand** [comment]
Hey @azihsoyn, are you still planning to make a PR at flutter's official flutter_ml_vision plugin with your custom model implementation? I think it would be a great addition to the plugin! (+ i could use it in a project of mine :stuck_out_tongue_closed_eyes:)
