### ISSUE TITLE
Is there an example for Image labeling?

### ISSUE THREAD

**Issue by baeharam** [azihsoyn/flutter_mlkit#32]
Do I have to write or Is there an example?

**Comment by azihsoyn** [comment]
I'm sorry, currently no example code.

In example code, rename `VisionText` to `VisionLabel` may works.

**Comment by baeharam** [comment]
@azihsoyn It works, Thx. I have a question, I'm getting started college final project using flutter ML kit. But after I tested text recognition and image labeling, I disappointed for its low-quality function. I'm considering now deeply, do you think it is a good choice to use firebase ML kit for my final project?

**Comment by azihsoyn** [comment]
@baeharam 
Firebase ML Kit supports cloud base detection (high accuracy) and custom model detection.

However, flutter_mlkit has not supported these features yet.

I don't know your final project, how about you consider native applications?

**Comment by baeharam** [comment]
@azihsoyn But google cloud vision api needs money, so we can't use. I'm looking for a idea using firebase ML kit. Our final project name is "Flutter application using Firebase ML kit". Thank you for ur answer. Also, I was impressed by your ml kit plugin open source, my goal is making flutter open source like you. THX!
