### ISSUE TITLE
cannot run on ios

### ISSUE THREAD

**Issue by sayurikunugi** [azihsoyn/flutter_mlkit#34]
hi. I want to use your FirebaseVisionTextDetector.
my app works fine on android, but when tried to run on ios, build failed with following errors.
what would you suppose wrong with my project?

Xcode's output:
↳
    === BUILD TARGET mlkit OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:1:
    In file included from /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.h:1:
    In file included from /Users/kunugisayuri/StudioProjects/insurance_card_reader/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:37:
    In file included from /Users/kunugisayuri/StudioProjects/insurance_card_reader/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/kunugisayuri/StudioProjects/insurance_card_reader/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:140:58: warning: this block declaration is not a prototype [-Wstrict-prototypes]
                          completionHandler:(nonnull void (^)())completionHandler;
                                                             ^
                                                              void
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:25:1: error: unknown type name 'FIRVisionTextDetector'; did you mean 'FIRVisionFaceDetector'?
    FIRVisionTextDetector *textDetector;
    ^~~~~~~~~~~~~~~~~~~~~
    FIRVisionFaceDetector
    In file included from /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:2:
    In file included from /Users/kunugisayuri/StudioProjects/insurance_card_reader/ios/Pods/Headers/Private/Firebase/Firebase.h:62:
    In file included from /Users/kunugisayuri/StudioProjects/insurance_card_reader/ios/Pods/Headers/Public/FirebaseMLVision/FirebaseMLVision/FirebaseMLVision.h:19:
    /Users/kunugisayuri/StudioProjects/insurance_card_reader/ios/Pods/Headers/Public/FirebaseMLVision/FirebaseMLVision/FIRVisionFaceDetector.h:22:12: note: 'FIRVisionFaceDetector' declared here
    @interface FIRVisionFaceDetector : NSObject
               ^
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:186:41: error: type argument 'FIRVisionText' must be a pointer (requires a '*')
    NSDictionary *visionTextToDictionary(id<FIRVisionText> visionText) {
                                            ^
                                                          *
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:186:38: error: type arguments cannot be applied to non-class type 'id'
    NSDictionary *visionTextToDictionary(id<FIRVisionText> visionText) {
                                         ^ ~~~~~~~~~~~~~~~
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:72:32: error: no visible @interface for 'FIRVision' declares the selector 'textDetector'
            textDetector = [vision textDetector];
                            ~~~~~~ ^~~~~~~~~~~~
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:82:43: error: type argument 'FIRVisionText' must be a pointer (requires a '*')
                                     for (id <FIRVisionText> feature in features) {
                                              ^
                                                            *
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:82:39: error: type arguments cannot be applied to non-class type 'id'
                                     for (id <FIRVisionText> feature in features) {
                                          ^  ~~~~~~~~~~~~~~~
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:188:17: error: property 'cornerPoints' not found on object of type '__strong id'
        [visionText.cornerPoints enumerateObjectsUsingBlock:^(NSValue * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
                    ^
    /Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit-0.6.0/ios/Classes/MlkitPlugin.m:195:35: error: property 'text' not found on object of type '__strong id'
                 @"text" : visionText.text,
                                      ^
    1 warning and 8 errors generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by azihsoyn** [comment]
Hi, @sayurikunugi ! Thanks to reporting!

In my project, the same issue happened.

**Comment by azihsoyn** [comment]
And official plugin has released. https://pub.dartlang.org/packages/firebase_ml_vision .

**Comment by azihsoyn** [comment]
https://firebase.google.com/docs/ml-kit/ios/recognize-text

ios mlkit library has updated. I'll fix it soon! Thanks!

**Comment by azihsoyn** [comment]
I released 0.6.1! https://pub.dartlang.org/packages/mlkit

Thanks reporting!

**Comment by sayurikunugi** [comment]
thanks, azihsoyn!
your plugin helps me a lot.

**Comment by sayurikunugi** [comment]
it worked fine, thank you!
I used the official plugin first, but it contained  same error.
I asked them about it, too, but you are faster to fix the problem.

**Comment by azihsoyn** [comment]
I'm glad I could help you.
