### ISSUE TITLE
Issue with detecting faces

### ISSUE THREAD

**Issue by rlee1990** [azihsoyn/flutter_mlkit#42]
When trying to detect faces in android I always receive this output:
`W/DynamiteModule(14227): Local module descriptor class for com.google.android.gms.vision.dynamite.face not found. I/DynamiteModule(14227): Considering local module com.google.android.gms.vision.dynamite.face:0 and remote module com.google.android.gms.vision.dynamite.face:0 D/FaceNativeHandle(14227): Cannot load feature, fall back to load whole module. W/DynamiteModule(14227): Local module descriptor class for com.google.android.gms.vision.dynamite not found. I/DynamiteModule(14227): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800 I/DynamiteModule(14227): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800 V/DynamiteModule(14227): Dynamite loader version >= 2, using loadModule2NoCrashUtils I/Vision (14227): Loading library libmobile_vision_face.so I/Vision (14227): libmobile_vision_face.so library load status: true`

Using a Galaxy note 8 in portrait and in landscape.
Also for IOS I receive this output:
`CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A mlkit
      R firebase_ml_vision
      - Flutter
      - camera
      - cloud_firestore
      - firebase_analytics
      - firebase_auth
      - firebase_core
      - firebase_database
      - firebase_storage
      - flutter_inapp_purchase
      - flutter_native_image
      - flutter_statusbar_manager
      - flutter_webview_plugin
      - geocoder
      - image_picker
      - location
      - path_provider
      - shared_preferences
      - url_launcher
      - video_player

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_database` from `.symlinks/plugins/firebase_database/ios`
    -> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios`
    -> Fetching podspec for `flutter_inapp_purchase` from `.symlinks/plugins/flutter_inapp_purchase/ios`
    -> Fetching podspec for `flutter_native_image` from `.symlinks/plugins/flutter_native_image/ios`
    -> Fetching podspec for `flutter_statusbar_manager` from `.symlinks/plugins/flutter_statusbar_manager/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `geocoder` from `.symlinks/plugins/geocoder/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `location` from `.symlinks/plugins/location/ios`
    -> Fetching podspec for `mlkit` from `.symlinks/plugins/mlkit/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Core":
      In snapshot (Podfile.lock):
        Firebase/Core (= 5.10.0)

      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Core

        mlkit (from `.symlinks/plugins/mlkit/ios`) was resolved to 0.6.3, which depends on
          Firebase/Core (~> 5.8.0)

    It seems like you've changed the constraints of dependency `Firebase/Core` inside your development pod `mlkit`.
    You should run `pod update Firebase/Core` to apply changes you've made.

    /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/resolver.rb:123:in `resolve'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:896:in `block in resolve_dependencies'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:894:in `resolve_dependencies'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:250:in `analyze'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:160:in `block in resolve_dependencies'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:159:in `resolve_dependencies'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:122:in `install!'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'`

**Comment by azihsoyn** [comment]
Thanks to reporting!

The podfile issue caused by version up of the firebase.
I'll fix it soon.

The Android issue needs more investigation. It may take a time.

**Comment by rlee1990** [comment]
Thanks for the update @azihsoyn I used the camera pub and the image picker pub to test for the face detection

**Comment by rlee1990** [comment]
@azihsoyn any update on this?

**Comment by azihsoyn** [comment]
@rlee1990
I released 0.8.0 for iOS dependency issue.

Android's orientation issue remains.
I'm planning support orientation option to detect image.

But it don't work currently.

Thanks

**Comment by rlee1990** [comment]
Thanks for the update

**Comment by azihsoyn** [comment]
Hi, @rlee1990 

In 0.8.1, Android detector treats Exif info.

This problem may be fixed.

**Comment by rlee1990** [comment]
Thanks @azihsoyn

**Comment by azihsoyn** [comment]
@rlee1990 Thanks for updating and trying!

Please try `pod update` at ios directory.

If the issue remains, show me your `ios/Podfile` and `pubspec.yaml`.

Thanks.

**Comment by rlee1990** [comment]
This is the pubspec file 
`dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.6.2+1
  firebase_database: ^1.0.5
  firebase_storage: ^1.0.4
  firebase_analytics: ^1.0.4
  firebase_core: ^0.2.5+1
  firebase_messaging: ^2.0.1
  firebase_admob: ^0.6.1+1
  cloud_firestore: ^0.8.1+1
#  firebase_ml_vision: ^0.2.0+1
  exifdart: ^0.7.0
  mlkit: ^0.8.1
  camera: ^0.2.4
  intl: "^0.15.6"
  country_code_picker: "^1.0.2"
  image_picker: "^0.4.4"
  uuid: ^1.0.3
  path_provider: "^0.4.1"
  flutter_native_image:
      git: https://github.com/btastic/flutter_native_image.git
  shared_preferences: "^0.4.3"
  flutter_cache_manager: ^0.2.0
  location: "^1.3.4"
  geocoder: "^0.1.1"
  cached_network_image: ^0.5.0
  transparent_image: "^0.1.0"
  firestore_helpers: ^2.0.5
  font_awesome_flutter: ^8.0.1
  carousel_pro: ^0.0.13
  zoomable_image: ^1.2.1+1
  flutter_swiper: ^1.1.3
  flutter_statusbar_manager: ^1.0.2
  flutter_range_slider: ^1.0.1
  image: ^2.0.4
  http: ^0.12.0
  flutter_webview_plugin: ^0.2.1+2
  native_device_orientation: ^0.0.2
  flutter_inapp_purchase: ^0.8.3
#  video_player: ^0.7.2
  intro_slider: ^1.0.7
#  chewie: ^0.7.0
  video_player:
            git:
              url: https://github.com/recastrodiaz/plugins.git
              path: packages/video_player
              ref: f0ade3cf3e366ec1e93139458f2bdf32d243b2be
            version: ^0.6.5

dev_dependencies:

  flutter_test:
    sdk: flutter`

this is the podfile

`# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end`

**Comment by rlee1990** [comment]
@azihsoyn any updates on this?

**Comment by azihsoyn** [comment]
Hi, @rlee1990!

I'm sorry late response.

I released 0.8.3 to resolve `target has transitive dependencies that include static frameworks` issue.

Please try the new version.

Thanks.

**Comment by rlee1990** [comment]
Thanks its all working now @azihsoyn
