### ISSUE TITLE
androidX compatibility

### ISSUE THREAD

**Issue by gimox** [azihsoyn/flutter_mlkit#55]
we need some changes for androidX compatibility:
- import android.support.annotation.NonNull;
- import android.support.media.ExifInterface;

**Comment by azihsoyn** [comment]
Hi, @gimox!

Thank you for using flutter_mlkit and issueing.

How about official flutter_ml_vision plugin?

If you know flutter_mlkit is un official plugin and you think continue to use, I try implement it.

**Comment by gimox** [comment]
i know, and it working good but i need a custom model!!!!

**Comment by azihsoyn** [comment]
Hi, @gimox

I published v0.10.0.
https://pub.dartlang.org/packages/mlkit

Thanks contributing 😄

**Comment by gimox** [comment]
perfect! 😄
