### ISSUE TITLE
issue with latest google-services dependency

### ISSUE THREAD

**Issue by tensor-programming** [azihsoyn/flutter_mlkit#59]
Building a project with the latest version of `google-services:4.2.0`, the one recommended on the firebase console causes a dependency error.  The newer `com.google.firebase:firebase-ml-common@19.0.0` doesn't let gradle compile due to your library being dependent upon `com.google.firebase:firebase-ml-vision@18.0.2`.  Might be worth making a note of in the readme if you don't plan on updating anytime soon.

**Comment by ihsanberahim** [comment]
@tensor-programming how you get  that google service version?. Today i only see `com.google.gms:google-services:4.2.0`

**Comment by tensor-programming** [comment]
Sorry, I mistyped, the version I was using is the `com.google.gms:google-services:4.2.0` you mentioned.

**Comment by liyoung1992** [comment]
I have a similar problem.~

**Comment by azihsoyn** [comment]
I'll release fix version in this week.

**Comment by ihsanberahim** [comment]
No pressure folk. Current, i using these and it works.
* https://pub.dev/packages/firebase_ml_vision
* https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx

**Comment by tensor-programming** [comment]
@ihsanberahim Thats fine, I've used the other library but it doesn't have the APIs that I need in it yet.  I want the natural language processor and the official flutterfire library simply doesn't have it yet; this library does though. 

@azihsoyn good to hear.

**Comment by liyoung1992** [comment]
Hi,@ihsanberahim @tensor-programming,
   I used official firebase_ml_vision  and this plugin,  This plugin is more comprehensive than the official plugin.
thanks @azihsoyn

**Comment by azihsoyn** [comment]
I'm sorry to late.

Now in progress.

Thanks.

**Comment by azihsoyn** [comment]
I released flutter_mlkit@0.12.0.

Please try it.

Thanks😄
