### ISSUE TITLE
Android minSdk version

### ISSUE THREAD

**Issue by Iampato** [azihsoyn/flutter_mlkit#68]
mlkit 0.13.0 only supports android version 24.0 and above ???

**Comment by azihsoyn** [comment]
Hi, @Iampato! Thank you for the question.

I'm sorry, in https://github.com/azihsoyn/flutter_mlkit/pull/60 I upgraded minSdkVersion.

Probably, minSdkVersion is not needed to upgrade.

I'll fix in next 0.13.1 or PR is welcome 😄

**Comment by azihsoyn** [comment]
Hi, @Iampato! 

I released fixed version.
https://pub.dev/packages/mlkit

Please try it!

Thanks 😄

**Comment by Iampato** [comment]
All Lord thank you
