### ISSUE TITLE
Local model

### ISSUE THREAD

**Issue by nominator** [azihsoyn/flutter_mlkit#75]
Is local model supported? I see the local model register method in the APIs but for interpreter invoke method the only argument it asks for is the remote one. Can you please share a timeline when the local model will be available for inference?

Thanks

**Comment by azihsoyn** [comment]
Hi, @nominator!

Currently, the local model is not supported.

It will take some time to implement.

**Comment by nominator** [comment]
ok thanks for the prompt reply. So if the remote model is downloaded once, I hope it is cached and used subsequently. I am hoping it does not get downloaded every time.

**Comment by nominator** [comment]
Also are there any callbacks to know when the model is downloaded and ready?

**Comment by azihsoyn** [comment]
> ok thanks for the prompt reply. So if the remote model is downloaded once, I hope it is cached and used subsequently. I am hoping it does not get downloaded every time.

Yes. And it can control condition for updating model.
https://github.com/azihsoyn/flutter_mlkit/blob/master/lib/mlkit.dart#L410

> Also are there any callbacks to know when the model is downloaded and ready?

Currently, not.

Thanks.

**Comment by azihsoyn** [comment]
Hi, @nominator!

Sorry, too late response.

Now flutter_mlkit supports local custom model.
https://github.com/azihsoyn/flutter_mlkit/pull/78

I released 0.14.0. 

Thanks 😄
