### ISSUE TITLE
It can work on Flutter Desktop ?

### ISSUE THREAD

**Issue by kalismeras61** [azihsoyn/flutter_mlkit#83]
Hello i want to planing to use mlkit for Windows. It can work on windows? or what will i need to do?

**Comment by azihsoyn** [comment]
Hi, @kalismeras61.

MLKit supports only ios and android.
https://firebase.google.com/docs/ml-kit/

Thanks.

**Comment by kalismeras61** [comment]
There is no way to use it? What do you think i use Cloud Api?

**Comment by azihsoyn** [comment]
Yes. No Web API provided.

**Comment by kalismeras61** [comment]
Thanks
